"""Initial schema

Revision ID: 205a46beff81
Revises: 
Create Date: 2026-04-22 16:35:30.845091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205a46beff81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_statistics')
    op.drop_index(op.f('ix_knowledge_asset_workflows_asset_id'), table_name='knowledge_asset_workflows')
    op.drop_table('knowledge_asset_workflows')
    op.alter_column('projects', 'bidding_company',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'agent_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'agent_phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'agent_email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'company_address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'bank_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'bank_account',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'confirm_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False,
               existing_server_default=sa.text("'待确认'"))
    op.alter_column('projects', 'confirm_feedback',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'confirmed_by',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'confirmed_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text('("user-001")'))
    op.alter_column('technical_cases', 'id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('technical_cases', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('technical_cases', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_technical_cases_title'), 'technical_cases', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technical_cases_title'), table_name='technical_cases')
    op.alter_column('technical_cases', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('technical_cases', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('technical_cases', 'id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('projects', 'user_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text('("user-001")'))
    op.alter_column('projects', 'confirmed_at',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'confirmed_by',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'confirm_feedback',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'confirm_status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'待确认'"))
    op.alter_column('projects', 'bank_account',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'bank_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'company_address',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'agent_email',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'agent_phone',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'agent_name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('projects', 'bidding_company',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.create_table('knowledge_asset_workflows',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('asset_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('owner', sa.VARCHAR(length=128), nullable=False),
    sa.Column('visibility', sa.VARCHAR(length=32), nullable=False),
    sa.Column('review_status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('reviewer', sa.VARCHAR(length=128), nullable=False),
    sa.Column('review_note', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_asset_workflows_asset_id'), 'knowledge_asset_workflows', ['asset_id'], unique=1)
    op.create_table('rule_statistics',
    sa.Column('rule_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('hit_count', sa.INTEGER(), nullable=False),
    sa.Column('confirmed_count', sa.INTEGER(), nullable=False),
    sa.Column('dismissed_count', sa.INTEGER(), nullable=False),
    sa.Column('modified_count', sa.INTEGER(), nullable=False),
    sa.Column('accuracy_rate', sa.FLOAT(), nullable=False),
    sa.Column('last_feedback_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('rule_name')
    )
    # ### end Alembic commands ###
