"""extend materials table with category content metadata

Revision ID: 34eefd50de02
Revises: e52f1fb8f2ea
Create Date: 2026-04-24 18:59:54.939221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34eefd50de02'
down_revision: Union[str, Sequence[str], None] = 'e52f1fb8f2ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('category', sa.String(length=64), server_default='other', nullable=False))
    op.add_column('materials', sa.Column('tags', sa.Text(), server_default='[]', nullable=False))
    op.add_column('materials', sa.Column('content', sa.Text(), server_default='', nullable=False))
    op.add_column('materials', sa.Column('organization', sa.String(length=256), server_default='', nullable=False))
    op.add_column('materials', sa.Column('acquired_date', sa.String(length=32), server_default='', nullable=False))
    op.add_column('materials', sa.Column('valid_until', sa.String(length=32), server_default='', nullable=False))
    op.add_column('materials', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('materials', sa.Column('metadata_json', sa.Text(), server_default='{}', nullable=False))
    op.add_column('materials', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'updated_at')
    op.drop_column('materials', 'metadata_json')
    op.drop_column('materials', 'is_active')
    op.drop_column('materials', 'valid_until')
    op.drop_column('materials', 'acquired_date')
    op.drop_column('materials', 'organization')
    op.drop_column('materials', 'content')
    op.drop_column('materials', 'tags')
    op.drop_column('materials', 'category')
    # ### end Alembic commands ###
