"""add_missing_columns_to_projects

Revision ID: 5a3549e4a73c
Revises: 62b79a85dd46
Create Date: 2026-05-05 11:37:22.460039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a3549e4a73c'
down_revision: Union[str, Sequence[str], None] = '62b79a85dd46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', sa.String(length=2000), nullable=False, server_default=''))
    op.add_column('projects', sa.Column('bid_template_files', sa.JSON(), nullable=False, server_default='[]'))
    op.alter_column('tenders', 'service_commitment',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenders', 'service_commitment',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.drop_column('projects', 'bid_template_files')
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###
