"""add_service_commitment_to_tenders

Revision ID: 62b79a85dd46
Revises: 9eb0db679f99
Create Date: 2026-04-25 19:11:45.571232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b79a85dd46'
down_revision: Union[str, Sequence[str], None] = '9eb0db679f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenders', sa.Column('service_commitment', sa.Text(), nullable=True, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenders', 'service_commitment')
    # ### end Alembic commands ###
