"""fix_schema_drift_add_missing_tables

Revision ID: b34a391c0222
Revises: bb2adecbb7f1
Create Date: 2026-04-24 15:59:28.516986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34a391c0222'
down_revision: Union[str, Sequence[str], None] = 'bb2adecbb7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('template_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('section_count', sa.Integer(), nullable=False),
    sa.Column('overall_progress', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_section_asset_refs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('section_id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('asset_title', sa.String(length=255), nullable=False),
    sa.Column('chunk_title', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_section_asset_refs_asset_id'), 'generation_section_asset_refs', ['asset_id'], unique=False)
    op.create_index(op.f('ix_generation_section_asset_refs_job_id'), 'generation_section_asset_refs', ['job_id'], unique=False)
    op.create_index(op.f('ix_generation_section_asset_refs_section_id'), 'generation_section_asset_refs', ['section_id'], unique=False)
    op.create_table('generation_sections_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('section_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('citations', sa.Integer(), nullable=False),
    sa.Column('todos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_sections_records_job_id'), 'generation_sections_records', ['job_id'], unique=False)
    op.create_table('knowledge_asset_index_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('triggered_by', sa.String(length=128), nullable=False),
    sa.Column('refreshed_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_asset_index_jobs_asset_id'), 'knowledge_asset_index_jobs', ['asset_id'], unique=False)
    op.create_table('project_asset_preferences',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('asset_title', sa.String(length=255), nullable=False),
    sa.Column('preference_mode', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_asset_preferences_asset_title'), 'project_asset_preferences', ['asset_title'], unique=False)
    op.create_index(op.f('ix_project_asset_preferences_project_id'), 'project_asset_preferences', ['project_id'], unique=False)
    op.create_table('project_decision_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.JSON(), nullable=True),
    sa.Column('rule_hits', sa.JSON(), nullable=True),
    sa.Column('ai_reasons', sa.JSON(), nullable=True),
    sa.Column('pending_checks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_decision_jobs_project_id'), 'project_decision_jobs', ['project_id'], unique=False)
    op.create_table('project_document_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('storage_backend', sa.String(length=32), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_document_versions_document_id'), 'project_document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_project_document_versions_project_id'), 'project_document_versions', ['project_id'], unique=False)
    op.create_table('project_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_documents_project_id'), 'project_documents', ['project_id'], unique=False)
    op.create_table('project_extracted_fields',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_extracted_fields_document_id'), 'project_extracted_fields', ['document_id'], unique=False)
    op.create_index(op.f('ix_project_extracted_fields_project_id'), 'project_extracted_fields', ['project_id'], unique=False)
    op.create_table('project_parse_sections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('page', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.String(length=16384), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_parse_sections_document_id'), 'project_parse_sections', ['document_id'], unique=False)
    op.create_index(op.f('ix_project_parse_sections_project_id'), 'project_parse_sections', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_parse_sections_project_id'), table_name='project_parse_sections')
    op.drop_index(op.f('ix_project_parse_sections_document_id'), table_name='project_parse_sections')
    op.drop_table('project_parse_sections')
    op.drop_index(op.f('ix_project_extracted_fields_project_id'), table_name='project_extracted_fields')
    op.drop_index(op.f('ix_project_extracted_fields_document_id'), table_name='project_extracted_fields')
    op.drop_table('project_extracted_fields')
    op.drop_index(op.f('ix_project_documents_project_id'), table_name='project_documents')
    op.drop_table('project_documents')
    op.drop_index(op.f('ix_project_document_versions_project_id'), table_name='project_document_versions')
    op.drop_index(op.f('ix_project_document_versions_document_id'), table_name='project_document_versions')
    op.drop_table('project_document_versions')
    op.drop_index(op.f('ix_project_decision_jobs_project_id'), table_name='project_decision_jobs')
    op.drop_table('project_decision_jobs')
    op.drop_index(op.f('ix_project_asset_preferences_project_id'), table_name='project_asset_preferences')
    op.drop_index(op.f('ix_project_asset_preferences_asset_title'), table_name='project_asset_preferences')
    op.drop_table('project_asset_preferences')
    op.drop_index(op.f('ix_knowledge_asset_index_jobs_asset_id'), table_name='knowledge_asset_index_jobs')
    op.drop_table('knowledge_asset_index_jobs')
    op.drop_index(op.f('ix_generation_sections_records_job_id'), table_name='generation_sections_records')
    op.drop_table('generation_sections_records')
    op.drop_index(op.f('ix_generation_section_asset_refs_section_id'), table_name='generation_section_asset_refs')
    op.drop_index(op.f('ix_generation_section_asset_refs_job_id'), table_name='generation_section_asset_refs')
    op.drop_index(op.f('ix_generation_section_asset_refs_asset_id'), table_name='generation_section_asset_refs')
    op.drop_table('generation_section_asset_refs')
    op.drop_table('generation_jobs')
    # ### end Alembic commands ###
