"""sync_schema_from_models

Revision ID: bb2adecbb7f1
Revises: 205a46beff81
Create Date: 2026-04-24 07:28:28.165900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb2adecbb7f1'
down_revision: Union[str, Sequence[str], None] = '205a46beff81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_providers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('protocol', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.drop_table('rule_statistics', if_exists=True)
    op.drop_index(op.f('ix_knowledge_asset_workflows_asset_id'), table_name='knowledge_asset_workflows', if_exists=True)
    op.drop_table('knowledge_asset_workflows', if_exists=True)
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('tender_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
        batch_op.alter_column('parse_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False)
        batch_op.alter_column('file_list',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False)
        batch_op.alter_column('node_status',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False)
        batch_op.alter_column('extracted_fields',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'extracted_fields',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'node_status',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'file_list',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'parse_status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'tender_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.create_table('knowledge_asset_workflows',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('asset_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('owner', sa.VARCHAR(length=128), nullable=False),
    sa.Column('visibility', sa.VARCHAR(length=32), nullable=False),
    sa.Column('review_status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('reviewer', sa.VARCHAR(length=128), nullable=False),
    sa.Column('review_note', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_asset_workflows_asset_id'), 'knowledge_asset_workflows', ['asset_id'], unique=1)
    op.create_table('rule_statistics',
    sa.Column('rule_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('hit_count', sa.INTEGER(), nullable=False),
    sa.Column('confirmed_count', sa.INTEGER(), nullable=False),
    sa.Column('dismissed_count', sa.INTEGER(), nullable=False),
    sa.Column('modified_count', sa.INTEGER(), nullable=False),
    sa.Column('accuracy_rate', sa.FLOAT(), nullable=False),
    sa.Column('last_feedback_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('rule_name')
    )
    op.drop_table('llm_providers')
    # ### end Alembic commands ###
