"""add document_score_history table

Revision ID: e52f1fb8f2ea
Revises: d79904bf3b48
Create Date: 2026-04-24 18:50:05.883445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52f1fb8f2ea'
down_revision: Union[str, Sequence[str], None] = 'd79904bf3b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_score_histories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('doc_id', sa.String(length=64), nullable=False),
    sa.Column('doc_kind', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('breakdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_score_histories_doc_id'), 'document_score_histories', ['doc_id'], unique=False)
    op.create_index(op.f('ix_document_score_histories_project_id'), 'document_score_histories', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_score_histories_project_id'), table_name='document_score_histories')
    op.drop_index(op.f('ix_document_score_histories_doc_id'), table_name='document_score_histories')
    op.drop_table('document_score_histories')
    # ### end Alembic commands ###
